<?php function renderPage ($page, $navigation) { ?>
	<?php if ( $navigation->accept($page) ): ?>
		<li class="<?php echo ($page->isActive(true) ? 'active' : '');?>
			<?php echo ($page->hasPages(true) ? 'dropdown' : '');?>">
			<?php if ($page->hasPages(true) ):
				$page->setClass('dropdown-toggle');
				echo '<a href="'.$page->getHref().'" class="'.$page->getClass().'" data-toggle="dropdown">' . $page->getLabel()  .'</a>';
				?>
					<ul class="dropdown-menu">
					<?php foreach ( $page->getPages() as $child ) :
						renderPage($child, $navigation);
					endforeach; ?>
					</ul>
			<?php else :
				echo '<a href="'.$page->getHref().'" class="'.$page->getClass().'">' . $page->getLabel()  .'</a>';
			endif; ?>
		</li>
	<?php endif; ?>
<?php } ?>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="<?php echo $this->url('home'); ?>"><i class="fi-cog"></i> <span>Біржа волонтерів України</span></a>
		</div>
		<div class="navbar-collapse navbar-inverse-collapse">
			<ul class="nav navbar-nav navbar-right">
				<?php foreach ( $this -> container as $page ) :
				renderPage ($page, $this -> navigation ());
				endforeach;	?>

			</ul>
		</div>
	</div>
</div>
